name: Lint, Typecheck and Build

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/pullrequest.yml'
      - 'apps/**'
      - 'packages/**'
      - 'tooling/**'
      - 'turbo.json'
      - 'package.json'
      - 'bun.lock'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/pullrequest.yml'
      - 'apps/**'
      - 'packages/**'
      - 'tooling/**'
      - 'turbo.json'
      - 'package.json'
      - 'bun.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-typecheck-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build
