name: Pull Request
permissions:
  contents: write
on:
  # workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Run linting
        run: npm run lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Run build packages
        run: npm run build
