name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  release-windows:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npx electron-forge make --platform=win32
        # npx electron-forge publish --platform=win32
      - name: Create Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/make/*
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
            ${{ github.event.head_commit.url }}
          draft: false
          prerelease: false
          generate_release_notes: true
  release-linux:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npx electron-forge make --platform=linux
        # npx electron-forge publish --platform=linux
      - name: Create Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/make/*
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
            ${{ github.event.head_commit.url }}
          draft: false
          prerelease: false
          generate_release_notes: true
  release-mac:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npx electron-forge make --platform=darwin
        # npx electron-forge publish --platform=darwin
      - name: Create Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/make/*
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
            ${{ github.event.head_commit.url }}
          draft: false
          prerelease: false
          generate_release_notes: true
