name: Release
on:
  push:
    tags: ['*']
  workflow_run:
    workflows: ['Version']
    branches: ['main']
    types:
      - completed
  workflow_dispatch:

jobs:
  release-windows:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        run: |
          npx electron-forge publish --platform=win32

  release-linux:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        run: |
          npx electron-forge publish --platform=linux

  release-mac:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        run: |
          npx electron-forge publish --platform=darwin --arch=universal
