name: Release
on:
  push:
    tags: ['*']
  workflow_run:
    workflows: ['Version']
    branches: ['master']
    types:
      - completed
  workflow_dispatch:

jobs:
  release-windows:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npx electron-forge make --platform=win32
          npx electron-forge publish --platform=win32
  release-linux:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npx electron-forge make --platform=linux
          npx electron-forge publish --platform=linux
  release-mac:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          npx electron-forge make --platform=darwin
          npx electron-forge publish --platform=darwin
