name: Version
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  version-patch:
    name: Generate Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email ""

      - name: Generate Version
        run: |
          npm version ${{ secrets.VERSION_CONTROL }} -m 'chore: release %s' --allow-same-version --no-commit-hooks

      - name: Push Version to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true

      - name: Push Version to tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true
          tags: true
