name: Version
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      version_control:
        description: "Version control type (patch, minor, major)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      version:
        description: "Version number"
        required: false
        default: ""
        type: string
jobs:
  version-patch:
    name: Generate Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email ""

      - name: Generate Version
        run: bash ./scripts/version.sh ${{ inputs.version_control || inputs.version || secrets.VERSION_CONTROL }}

      - name: Commit and tag
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")
          git add -A
          git commit -m "chore: release ${NEW_VERSION}" --no-verify
          git tag "v${NEW_VERSION}"

      - name: Push Version to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true

      - name: Push Version to tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true
          tags: true
